### ISSUE TITLE
Deberias de hacer que la condicion se evalue cuando le das a guardar, porque cuando vas a crear una nueva prioridad  no te debería de aparecer un error sin ni siquiere poner nada en el campo

### ISSUE THREAD

**Issue by AlexanderST01** [Yudelkaa/RegistroPrioridadesKt#6]
https://github.com/Yudelkaa/RegistroPrioridadesKt/blob/74a28543bf06d0c011022d1cc8cec3c5411c5b6a/app/src/main/java/edu/ucne/prioridades/presentation/prioridad/PrioridadScreen.kt#L44

**Comment by Yudelkaa** [comment]
De acuerdo, muchas gracias. Será corregida tu observación🙏🏽
