### ISSUE TITLE
Simplemente es algo estético, pero puedes poner el content debajo, de esta forma: Scaffold(TopAppBar, etc ){  //content// innerPadding ->}

### ISSUE THREAD

**Issue by AlexanderST01** [Yudelkaa/RegistroPrioridadesKt#7]
https://github.com/Yudelkaa/RegistroPrioridadesKt/blob/74a28543bf06d0c011022d1cc8cec3c5411c5b6a/app/src/main/java/edu/ucne/prioridades/presentation/prioridad/PrioridadScreen.kt#L66

**Comment by Yudelkaa** [comment]
Lo corregiré así, gracias!
